name: Deploy App
description: Composite action to deploy an app

runs:
  using: composite
  steps:
    - name: Deploy
      shell: bash
      run: |
        echo "This is a placeholder action"
