name: Go Workflow

on:
  workflow_call:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  versioning:
    name: Determine
    uses: suspectsoftware/action-semantic-versioning/.github/workflows/main.yml@v1

  build_pullrequest:
    name: Build (PR)
    runs-on: ubuntu-latest
    needs: [versioning]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Build
        uses: ./.github/actions/composites/go-build
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [versioning]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ${{ github.action_path }}/.github/actions/composites/go-build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [versioning]
    steps:
      - name: Test
        uses: ./.github/actions/composites/go-test

  deploy_test:
    name: Deploy Test
    runs-on: ubuntu-latest
    needs: [build, test, versioning]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Deploy
        uses: ./.github/actions/composites/deploy

  deploy_prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: [build, test, versioning]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Deploy
        uses: ./.github/actions/composites/deploy
  