name: Go Workflow

on:
  workflow_call:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  versioning:
    name: Determine
    uses: suspectsoftware/action-semantic-versioning/.github/workflows/main.yml@v1

  build_pullrequest:
    name: Build (PR)
    runs-on: ubuntu-latest
    needs: [versioning]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Build
        uses: suspectsoftware/workflow-examples/.github/actions/composites/go-build@main
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [versioning]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Build
        uses: suspectsoftware/workflow-examples/.github/actions/composites/go-build@main
        with:
          binary-path: main

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [versioning]
    steps:
      - name: Test
        uses: suspectsoftware/workflow-examples/.github/actions/composites/go-test@main

  deploy_test:
    name: Deploy Test
    runs-on: ubuntu-latest
    needs: [build, test, versioning]
    if: ${{ github.event_name != 'pull_request' && github.ref != 'refs/heads/main' }}
    steps:
      - name: Deploy
        uses: suspectsoftware/workflow-examples/.github/actions/composites/deploy@main

  deploy_prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: [build, test, versioning]
    if: ${{ github.event_name != 'pull_request'  && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy
        uses: suspectsoftware/workflow-examples/.github/actions/composites/deploy@main
  